resolver: lts-20.26
# resolver: lts-21.22 # ghc 9.4.8

packages:
- ./identifiers
- ./render
- ./threatlevel-common
- ./threatlevel-url
- ./threatlevel-css
- ./threatlevel-js
- ./threatlevel-web
- ./threatlevel-unsorted

extra-deps:
- rapid-0.1.4@sha256:b7e23399d49f0d8a6c79903ca822ac3e5827646b47b2b4e5716684179bd261ec
- git: https://github.com/eyeinsky/fixedlist.git
  commit: 2f4642d8c697d9666fbf579b8d4d5616c3a397ec

nix:
  enable: true
  packages: [ zlib ]
