name: threatlevel-web
version: '0.2.0.0'
category: Web
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: GPL-2
dependencies:
- base
- cookie
- lens-aeson
- directory
- transformers
- wreq
- vector
- lens
- aeson
- async
- blaze-builder
- boomerang
- bytestring
- case-insensitive
- containers
- dlist
- file-embed
- hashable
- http-types
- http-client
- identifiers
- mime-types
- mtl
- network
- tagged
- template-haskell
- text
- text-format
- unordered-containers
- wai
- wai-extra
- warp
- warp-tls
- render
- rapid
- cryptonite
- memory
- base64-bytestring
- process
- time
- mwc-random
- data-default
- multiline
- websockets
- wai-websockets
- threatlevel-common
- threatlevel-browser
- threatlevel-url
- threatlevel-css
- threatlevel-js

library:
  source-dirs:
  - .
  exposed-modules:
  - HTTP.Common
  - HTTP.Header
  - HTTP.Response
  - HTTP.Response.InlineFile
  - HTTP

  - SVG
  - SVG.CSS
  - HTML
  - Web.CSS
  - Web.Monad
  - XML
  - XML.Core

  - Sessions
  - JW.T

  # WebAPIs
  - IndexedDB.IDB
  - DOM.Core
  - DOM.Event
  - DOM.JS
  - DOM
  - PWA
  - WebSockets
  - WebAPIs.DOM

  # Server
  - Server
  - Server.Run
  - Server.Static
  - Server.API
  - Server.Response
  - Server.Hot
  - Server.Wai

  - X
  - X.Prelude
  - X.Cookie
  - X.DOM
  - X.Template
  - X.Template.V2
  - X.Template.V3
  - X.Auth.Google
  - X.Google.Maps
  - X.Google.Spreadsheet
  - X.Widgets
  - X.Widgets.Menu
  - X.Wai
  ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-missing-signatures
  - -Wno-type-defaults

tests:
  test:
    main: manual-browser-tests.hs
    source-dirs:
    - tests

default-extensions:
- Arrows
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- DerivingStrategies
- EmptyDataDecls
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeInType
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
