name: threatlevel-web
version: '0.2.0.0'
category: Web
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: GPL-2

library:
  source-dirs: .
  exposed-modules:

  - Web.DSL
  - Web.DSL.Helpers

  # Lib
  - Web.Lib.CSS_HTML
  - Web.Lib.HTML_URL
  - Web.Lib.HTML
  - Web.Lib.URL_CSS

  # WebAPIs
  - Web.Apis.DOM
  - Web.Apis.Fetch
  - Web.Apis.IDB
  - Web.Apis.PWA
  - Web.Apis.CustomElement
  - Web.Apis.WebSocket
  - Web.X

  - DOM.Core
  - DOM.JS

  - SVG
  - SVG.CSS
  - HTML
  - XML
  - XML.Core

  - Web

  # Encrypted static site
  - Web.Secret

  ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-missing-signatures
  - -Wno-type-defaults

tests:
  test:
    main: manual-browser-tests.hs
    source-dirs:
    - tests

language: GHC2021
default-extensions:
- DataKinds
- DefaultSignatures
- DerivingVia
- ExtendedDefaultRules
- FunctionalDependencies
- GADTs
- LambdaCase
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- QuasiQuotes
- RecursiveDo
- TemplateHaskell
- TypeFamilies
- TypeInType
- UndecidableInstances

dependencies:
- aeson
- base
- base64-bytestring
- bytestring
- containers
- cookie
- cryptonite
- data-default
- directory
- dlist
- file-embed
- hashable
- http-types
- identifiers
- lens
- lens-aeson
- memory
- mtl
- neat-interpolation
- process
- rapid
- render
- template-haskell
- text
- time
- transformers
- unordered-containers
- wai
- wai-extra
- wai-websockets
- warp
- warp-tls
- websockets
- wreq
- threatlevel-common
- threatlevel-url
- threatlevel-css
- threatlevel-js
