name: threatlevel-unsorted
version: '0.2.0.0'
category: Web
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: GPL-2

dependencies:
- base
- threatlevel-web

library:
  source-dirs: .
  exposed-modules:
  - Web.Monad

  # Server
  - Server
  - Server.Run
  - Server.Static
  - Server.API
  - Server.Response
  - Server.Hot
  - Server.Wai
  - Server.Sessions
  - Server.WebSocket

  - X.Cookie

  ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-missing-signatures
  - -Wno-type-defaults

tests:
  test:
    main: manual-browser-tests.hs
    source-dirs:
    - tests

default-extensions:
- Arrows
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- DerivingVia
- EmptyDataDecls
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeInType
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
