name: threatlevel-unsorted
version: '0.2.0.0'
category: Web
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: GPL-2

dependencies:
- base
- threatlevel-web

library:
  source-dirs: .
  exposed-modules:
  - Web.Monad

  # Server
  - Server
  - Server.Run
  - Server.Static
  - Server.API
  - Server.Response
  - Server.Hot
  - Server.Wai
  - Server.Sessions
  - Server.WebSocket

  - X.Cookie

  ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-missing-signatures
  - -Wno-type-defaults

language: GHC2021
default-extensions:
- DataKinds
- DefaultSignatures
- DerivingVia
- ExtendedDefaultRules
- FunctionalDependencies
- GADTs
- LambdaCase
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- QuasiQuotes
- RecursiveDo
- TemplateHaskell
- TypeFamilies
- TypeInType
- UndecidableInstances
