name: threatlevel-url
version: 0.0.1
synopsis: Url
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: MIT
github: eyeinsky/threatlevel/threatlevel-url
category: Web

dependencies:
- base
- lens
- text
- mtl
- attoparsec
- http-types
- render
- template-haskell

library:
  source-dirs: .
  exposed-modules:
    - URL
    - URL.Core
    - URL.Parse
    - URL.Render
    - URL.TH

language: GHC2021
default-extensions:
- DataKinds
- DefaultSignatures
- DerivingVia
- ExtendedDefaultRules
- FunctionalDependencies
- GADTs
- LambdaCase
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- QuasiQuotes
- RecursiveDo
- TemplateHaskell
- TypeFamilies
- TypeInType
