name: threatlevel-url
version: 0.0.1
synopsis: Url
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: MIT
github: eyeinsky/threatlevel/threatlevel-url
category: Web

dependencies:
  - base
  - lens
  - text
  - mtl
  - attoparsec
  - http-types
  - render
  - template-haskell

library:
  exposed-modules:
    - URL
    - URL.Core
    - URL.Parse
    - URL.Render
    - URL.TH

default-extensions:
  - Arrows
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - EmptyDataDecls
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - ImportQualifiedPost
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeInType
  - TypeOperators
  - TypeSynonymInstances
