name: multiline
version: '0.1.0.0'
category: Text
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: GPL-2
extra-source-files:
- CHANGELOG.md

dependencies:
- base
- template-haskell

library:
  source-dirs: .
  exposed-modules:
  - Data.Text.Multiline
