name: identifiers
version: '0.1.0.0'
category: Web
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: BSD3
homepage: https://github.com/githubuser/identifiers#readme
extra-source-files:
- README.md

default-extensions:
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TypeFamilies

dependencies:
- base
- text
- mtl
- lens

library:
  source-dirs: .
  exposed-modules:
  - Identifiers

benchmarks:
  identifier-source:
    main: identifier-source.hs
    source-dirs: benchmarks
    ghc-options:
    - -w
    - -O2
    - -threaded
    dependencies:
    - identifiers
    - criterion
