name: render
version: '0.1.0.0'
license: BSD3

dependencies:
- base
- bytestring
- mtl
- text

default-extensions:
- ScopedTypeVariables
- TypeFamilies
- OverloadedStrings

library:
  exposed-modules:
  - Render
