name: threatlevel-js
version: '0.1.0.0'
category: Language
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: GPL-2

dependencies:
- aeson
- base
- containers
- data-default
- hashable
- lens
- mtl
- template-haskell
- text
- time
- unordered-containers
- polysemy

- identifiers
- render
- threatlevel-common

library:
  source-dirs: .
  exposed-modules:
  # JavaScript syntax, DSL and meta
  - JS.Syntax
  - JS.DSL
  - JS.DSL.Syntax
  - JS.DSL.Core
  - JS.DSL.MTL.Effect
  - JS.DSL.MTL.Mono
  - JS.Derive
  - JS.Roundtrip
  - JS.TH

  # JavaScript standard built-in objects
  - JS.API
  - JS.BuiltIns.JSON
  - JS.BuiltIns.Date
  - JS.BuiltIns.String
  - JS.BuiltIns.Number
  - JS.BuiltIns.Object
  - JS.BuiltIns
  - JS.BuiltIns.Full

  # WebAPIs
  - JS.Event
  - JS.Console

  - JS
  - JS.Lib
  - JS.Lib.Sleep
  - JS.Lib.Async

  ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-missing-signatures
  - -Wno-type-defaults

language: GHC2021
default-extensions:
- DataKinds
- DefaultSignatures
- DerivingVia
- ExtendedDefaultRules
- FunctionalDependencies
- GADTs
- LambdaCase
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- QuasiQuotes
- RecursiveDo
- TemplateHaskell
- TypeFamilies
- TypeInType
- UndecidableInstances
