name: web
version: '0.2.0.0'
category: Language
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: GPL-2
dependencies:
- base
- cookie
- lens-aeson
- directory
- transformers
- wreq
- vector
- lens
- aeson
- async
- blaze-builder
- boomerang
- bytestring
- case-insensitive
- containers
- dlist
- file-embed
- hashable
- http-types
- http-client
- identifiers
- mime-types
- mtl
- network
- tagged
- template-haskell
- text
- text-format
- unordered-containers
- wai
- wai-extra
- warp
- warp-tls
- web-browser
- web-url
- render
- rapid
- cryptonite
- memory
- base64-bytestring
- process
- time
- mwc-random
- data-default
- multiline
- websockets
- wai-websockets

library:
  source-dirs:
  - .
  exposed-modules:
  - HTTP.Common
  - HTTP.Header
  - HTTP.Response
  - HTTP.Response.InlineFile
  - HTTP
  - Warp_Helpers
  - CSS
  - SVG
  - HTML
  - Web.CSS
  - Web.Endpoint
  - Web.Monad
  - Web.Response
  - XML
  - XML.Core

  # JavaScript syntax, DSL and meta
  - JS.Syntax
  - JS.DSL
  - JS.Derive
  - JS.Roundtrip
  - Sessions
  - JS.TH

  # JavaScript standard built-in objects
  - JS.API
  - JW.T
  - JS.BuiltIns.JSON
  - JS.BuiltIns.Date
  - JS.BuiltIns.String
  - JS.BuiltIns.Number
  - JS.BuiltIns.Object
  - JS.BuiltIns

  # JavaScript APIs
  - JS.Event

  # WebAPIs
  - JS.Console
  - IndexedDB.IDB
  - DOM.Core
  - DOM.Event
  - DOM.JS
  - DOM
  - PWA
  - WebSockets

  - JS
  - JS.Lib
  - JS.Lib.Sleep
  - JS.Lib.Async

  # pre-X
  - Static
  - Hot

  - X
  - X.Prelude
  - X.Cookie
  - X.DOM
  - X.Template
  - X.Template.V2
  - X.Auth.Google
  - X.Google.Maps
  - X.Google.Spreadsheet
  - X.Widgets
  - X.Widgets.Menu
  - X.Wai
  ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-missing-signatures
  - -Wno-type-defaults

tests:
  test:
    main: manual-browser-tests.hs
    source-dirs:
    - tests
default-extensions:
- Arrows
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- DerivingStrategies
- EmptyDataDecls
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeInType
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
